### ISSUE TITLE
LC Token

### ISSUE THREAD

**Issue by davidyapdy** [nmstoker/lockebot#8]
First of all, thanks for posting this. This is very helpful for us to switch from api.ai to our own intent parser. When I was going through your code, I'm trying to figure out what is the LC token? Thanks. Oh! I wonder if you can do a flask version of it :)

**Comment by nmstoker** [comment]
Hi David,
LC token is if you want to use [Let's Chat](https://sdelements.github.io/lets-chat/). It has the advantage of being open source and you can self-host (so potentially useful in an in-house private date scenario).

Regarding flask question, I'm actually refactoring the code a little right now and have a Facebook Messenger integration that uses flask (I'm not experienced with flask but it was fairly straight-forward to get something basic out). I hope to get the refactored code out by Monday.

Kind regards,
Neil

**Comment by davidyapdy** [comment]
It's alright, I'll can do it and could contribute in this project. But I'll be doing it in Sanic instead. It's like flask but it's 8X faster. Kinda like node after we got async in 3.5. Hope you don't mind me using some of the code here and made a sanic version out of it. Could be a good practice for me :)

**Comment by nmstoker** [comment]
Certainly, by all means! Pleased if the code is at all useful.
BTW, here's some more info on the LC token (you get it from within Let's Chat and just paste that in the code) https://github.com/sdelements/lets-chat/wiki/API%3A-Authentication

**Comment by davidyapdy** [comment]
Thanks Neil for being cool! Let's stay in touch. Btw, would love if you could check us out at https://getaudrey.com

**Comment by nmstoker** [comment]
One point to note: Rasa NLU is not yet Python 3 compatible, so much as I'd like this to work in 3, it's 2.7 currently, although there was a chap who got an older version working on 3. It looks like Sanic requires 3.5+.

LockeBot and Rasa could possibly be decoupled if the http interface were used: http://rasa-nlu.readthedocs.io/en/latest/http.html but not something I've looked at (yet...!)

Audrey looks v interesting!

**Comment by davidyapdy** [comment]
Probably it's because MITIE do not have 3.5 support. However Spacy and scikit-learn (not-stable) do. I'll probably update RASA's spacy and scikit-learn to support 3.5 myself and see if it works. Hopefully it does. I'm liking the async so far. Plus MITIE is kinda slow compared to Spacy.
